- name: stop/rm grafana docker container
  docker_container:
    state: absent
    keep_volumes: yes
    name: grafana

- name: grafana/grafana image
  docker_image:
    name: grafana/grafana:latest
    state: present

- name: docker container
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart_policy: unless-stopped
    volumes:
      - "grafana-storage:/var/lib/grafana"
    networks:
      - name: influx
    ports:
      - "80:3000"
    env:
      GF_SERVER_DOMAIN: "{{grafana_domain|default(inventory_hostname)}}"
      GF_SERVER_ROOT_URL: "http://{{grafana_domain|default(inventory_hostname)}}/"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password|default(lookup('password', 'grafana_admin_password chars=ascii_letters')) }}"
      GF_USERS_ALLOW_SIGN_UP: false
      GF_USERS_ALLOW_ORG_CREATE: false
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_NAME: "Anon Org"
      GF_SMTP_ENABLED: true
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_SKIP_VERIFY: true
      GF_SMTP_FROM_ADDRESS: "no-reply@{{grafana_domain|default(inventory_hostname)}}"
      GF_INSTALL_PLUGINS: raintank-worldping-app,ryantxu-ajax-panel
