# this needs to be set for vips. but its only really here to remind you about it.  environment:
# GI_TYPELIB_PATH: /usr/local/lib/girepository-1.0

# include variable files...
# - name: "include vars: {{item}}"
#   include_vars:
#     file: "{{item}}"
#   no_log: true
#   with_items:
#     - influxdb_vars.yml
#   tags: always

- include_role:
    name: common
    tasks_from: harden.yml
  vars:
    tcp_ports: [22, 80, 443, 8086]
    udp_ports: [22, 80, 443, 8086]
  tags: net, harden

- include_tasks: mount_volumes.yml dev="/dev/vdc1"
  tags: base, storage, physical

- import_tasks: tasks/docker.yml
  tags: docker, setup
#
- include_tasks: software_modules/influxdb.yml
  tags: docker, influxdb, influx, tick
#
- include_tasks: software_modules/smtp.yml
  tags: docker, tick, smtp

- include_tasks: software_modules/kapacitor.yml version=1.3.1
  tags: docker, tick, kapacitor

- include_tasks: software_modules/grafana.yml
  tags: docker, grafana, tick
